### ISSUE TITLE
error when importing in Python 3

### ISSUE THREAD

**Issue by rjmorris** [ralhei/pyRserve#9]
`import pyRserve` produces an error in Python 3.4.1. The problem is the `except` statement in `rconn.py` on line 79:

```python
except socket.error, msg:
```

Using the comma in `except` statements is invalid syntax in Python 3. Using `as` in place of the comma works in Python 3, but I'm not sure if it will work in the older supported Python versions.

**Comment by eeue56** [comment]
`except..as` was [introduced](https://docs.python.org/2/whatsnew/2.6.html#pep-3110-exception-handling-changes) in Python 2.6. I've created a PR that will fix this issue - #10

**Comment by ralhei** [comment]
solved by your pull request #10
